---
title: "lab07_assignment"
format: 
  html:
    embed-resources: true
editor: visual
---

# Group Assignment Lab 7

## Libraries

```{r}
library(tidyverse)
library(broom)
```

## Load Data

```{r}
#| message: false
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

## Investigate data

The data is a breast cancer

```{r}
str(biopsy)
```

## Data Wrangling

Select numeric values, scale data and perform PCA

```{r}
pca_fit <- biopsy |>
  select(where(is.numeric)) |>
  scale() |>
  prcomp() 
```

## Look at the data in PC coordinates

Looking at the fitted dataset firstly

```{r}
pca_fit
```

Plotting the data in PC coordinates

```{r}
pca_fit |>
  augment(biopsy) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) +
  geom_point(size = 1) +
  scale_color_manual(values = c(Malignant = "red", Benign = "green")) +
  labs(title = "Data in PC coordinates") +
  theme_classic() + background_grid()
  
```

## Look at the rotation matrix

## Look at the variance explained by each PC
